%% Import data from text file.
% Script for importing data from the following text file:
%
%    /home/mlamonta/git/myhackrf/src/RADAR/tx.csv
%
% To extend the code to different selected data or a different text file,
% generate a function instead of a script.

% Auto-generated by MATLAB on 2016/04/23 15:55:13

%% Initialize variables.
filename = '/home/mlamonta/git/myhackrf/src/RADAR/tx.csv';
delimiter = ',';

%% Format string for each line of text:
%   column1: double (%f)
%	column2: double (%f)
%   column3: double (%f)
% For more information, see the TEXTSCAN documentation.
formatSpec = '%f%f%f%[^\n\r]';

%% Open the text file.
fileID = fopen(filename,'r');

%% Read columns of data according to format string.
% This call is based on the structure of the file used to generate this
% code. If an error occurs for a different file, try regenerating the code
% from the Import Tool.
dataArray = textscan(fileID, formatSpec, 'Delimiter', delimiter, 'EmptyValue' ,NaN, 'ReturnOnError', false);

%% Close the text file.
fclose(fileID);

%% Post processing for unimportable data.
% No unimportable data rules were applied during the import, so no post
% processing code is included. To generate code which works for
% unimportable data, select unimportable cells in a file and regenerate the
% script.

%% Allocate imported array to column variable names
tx_t = dataArray{:, 1};
tx_sig = complex(dataArray{:, 2}, dataArray{:, 3});

clc
figure(10);
subplot(211)
plot(tx_t * 1e6, real(tx_sig)); hold on;
plot(tx_t * 1e6, imag(tx_sig), 'r');
title('Waveform - Time')
xlabel('Time (us)')
ylabel('Magnitude (counts)')

subplot(212)
fs = 8e6;
plot(linspace(-fs/2,fs/2,length(tx_sig))/1e6, 10*log10(fftshift(abs(fft(tx_sig)))))
title('Waveform - FFT')
xlabel('Frequency (MHz)')
ylabel('dB')


%% Clear temporary variables
clearvars filename delimiter formatSpec fileID dataArray ans;