/**
 * @fileoverview
 * @enhanceable
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!

goog.provide('proto.FFT_Packet');

goog.require('jspb.BinaryReader');
goog.require('jspb.BinaryWriter');
goog.require('jspb.Message');


/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.FFT_Packet = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.FFT_Packet.repeatedFields_, null);
};
goog.inherits(proto.FFT_Packet, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  proto.FFT_Packet.displayName = 'proto.FFT_Packet';
}
/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.FFT_Packet.repeatedFields_ = [1,2];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.FFT_Packet.prototype.toObject = function(opt_includeInstance) {
  return proto.FFT_Packet.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.FFT_Packet} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.FFT_Packet.toObject = function(includeInstance, msg) {
  var f, obj = {
    freqBinsHzList: jspb.Message.getRepeatedField(msg, 1),
    fftList: jspb.Message.getRepeatedFloatingPointField(msg, 2)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.FFT_Packet}
 */
proto.FFT_Packet.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.FFT_Packet;
  return proto.FFT_Packet.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.FFT_Packet} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.FFT_Packet}
 */
proto.FFT_Packet.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {number} */ (reader.readUint64());
      msg.addFreqBinsHz(value);
      break;
    case 2:
      var value = /** @type {number} */ (reader.readDouble());
      msg.addFft(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.FFT_Packet.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.FFT_Packet.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.FFT_Packet} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.FFT_Packet.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getFreqBinsHzList();
  if (f.length > 0) {
    writer.writeRepeatedUint64(
      1,
      f
    );
  }
  f = message.getFftList();
  if (f.length > 0) {
    writer.writeRepeatedDouble(
      2,
      f
    );
  }
};


/**
 * repeated uint64 freq_bins_hz = 1;
 * @return {!Array.<number>}
 */
proto.FFT_Packet.prototype.getFreqBinsHzList = function() {
  return /** @type {!Array.<number>} */ (jspb.Message.getRepeatedField(this, 1));
};


/** @param {!Array.<number>} value */
proto.FFT_Packet.prototype.setFreqBinsHzList = function(value) {
  jspb.Message.setField(this, 1, value || []);
};


/**
 * @param {!number} value
 * @param {number=} opt_index
 */
proto.FFT_Packet.prototype.addFreqBinsHz = function(value, opt_index) {
  jspb.Message.addToRepeatedField(this, 1, value, opt_index);
};


proto.FFT_Packet.prototype.clearFreqBinsHzList = function() {
  this.setFreqBinsHzList([]);
};


/**
 * repeated double fft = 2;
 * @return {!Array.<number>}
 */
proto.FFT_Packet.prototype.getFftList = function() {
  return /** @type {!Array.<number>} */ (jspb.Message.getRepeatedFloatingPointField(this, 2));
};


/** @param {!Array.<number>} value */
proto.FFT_Packet.prototype.setFftList = function(value) {
  jspb.Message.setField(this, 2, value || []);
};


/**
 * @param {!number} value
 * @param {number=} opt_index
 */
proto.FFT_Packet.prototype.addFft = function(value, opt_index) {
  jspb.Message.addToRepeatedField(this, 2, value, opt_index);
};


proto.FFT_Packet.prototype.clearFftList = function() {
  this.setFftList([]);
};


