/**
 * @fileoverview
 * @enhanceable
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!

goog.provide('proto.Packet');

goog.require('jspb.BinaryReader');
goog.require('jspb.BinaryWriter');
goog.require('jspb.Message');
goog.require('proto.FFT_Packet');
goog.require('proto.IQ_Packet');
goog.require('proto.PDW_Packet');
goog.require('proto.Packet_Header');


/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.Packet = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, proto.Packet.oneofGroups_);
};
goog.inherits(proto.Packet, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  proto.Packet.displayName = 'proto.Packet';
}
/**
 * Oneof group definitions for this message. Each group defines the field
 * numbers belonging to that group. When of these fields' value is set, all
 * other fields in the group are cleared. During deserialization, if multiple
 * fields are encountered for a group, only the last value seen will be kept.
 * @private {!Array<!Array<number>>}
 * @const
 */
proto.Packet.oneofGroups_ = [[2,3,4]];

/**
 * @enum {number}
 */
proto.Packet.BodyCase = {
  BODY_NOT_SET: 0,
  IQ_PACKET: 2,
  FFT_PACKET: 3,
  PDW_PACKET: 4
};

/**
 * @return {proto.Packet.BodyCase}
 */
proto.Packet.prototype.getBodyCase = function() {
  return /** @type {proto.Packet.BodyCase} */(jspb.Message.computeOneofCase(this, proto.Packet.oneofGroups_[0]));
};



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.Packet.prototype.toObject = function(opt_includeInstance) {
  return proto.Packet.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.Packet} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.Packet.toObject = function(includeInstance, msg) {
  var f, obj = {
    header: (f = msg.getHeader()) && proto.Packet_Header.toObject(includeInstance, f),
    iqPacket: (f = msg.getIqPacket()) && proto.IQ_Packet.toObject(includeInstance, f),
    fftPacket: (f = msg.getFftPacket()) && proto.FFT_Packet.toObject(includeInstance, f),
    pdwPacket: (f = msg.getPdwPacket()) && proto.PDW_Packet.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.Packet}
 */
proto.Packet.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.Packet;
  return proto.Packet.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.Packet} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.Packet}
 */
proto.Packet.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new proto.Packet_Header;
      reader.readMessage(value,proto.Packet_Header.deserializeBinaryFromReader);
      msg.setHeader(value);
      break;
    case 2:
      var value = new proto.IQ_Packet;
      reader.readMessage(value,proto.IQ_Packet.deserializeBinaryFromReader);
      msg.setIqPacket(value);
      break;
    case 3:
      var value = new proto.FFT_Packet;
      reader.readMessage(value,proto.FFT_Packet.deserializeBinaryFromReader);
      msg.setFftPacket(value);
      break;
    case 4:
      var value = new proto.PDW_Packet;
      reader.readMessage(value,proto.PDW_Packet.deserializeBinaryFromReader);
      msg.setPdwPacket(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.Packet.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.Packet.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.Packet} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.Packet.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getHeader();
  if (f != null) {
    writer.writeMessage(
      1,
      f,
      proto.Packet_Header.serializeBinaryToWriter
    );
  }
  f = message.getIqPacket();
  if (f != null) {
    writer.writeMessage(
      2,
      f,
      proto.IQ_Packet.serializeBinaryToWriter
    );
  }
  f = message.getFftPacket();
  if (f != null) {
    writer.writeMessage(
      3,
      f,
      proto.FFT_Packet.serializeBinaryToWriter
    );
  }
  f = message.getPdwPacket();
  if (f != null) {
    writer.writeMessage(
      4,
      f,
      proto.PDW_Packet.serializeBinaryToWriter
    );
  }
};


/**
 * required Packet_Header header = 1;
 * @return {!proto.Packet_Header}
 */
proto.Packet.prototype.getHeader = function() {
  return /** @type{!proto.Packet_Header} */ (
    jspb.Message.getWrapperField(this, proto.Packet_Header, 1, 1));
};


/** @param {!proto.Packet_Header} value */
proto.Packet.prototype.setHeader = function(value) {
  jspb.Message.setWrapperField(this, 1, value);
};


proto.Packet.prototype.clearHeader = function() {
  jspb.Message.setField(this, 1, undefined);
};


/**
 * Returns whether this field is set.
 * @return {!boolean}
 */
proto.Packet.prototype.hasHeader = function() {
  return jspb.Message.getField(this, 1) != null;
};


/**
 * optional IQ_Packet iq_packet = 2;
 * @return {?proto.IQ_Packet}
 */
proto.Packet.prototype.getIqPacket = function() {
  return /** @type{?proto.IQ_Packet} */ (
    jspb.Message.getWrapperField(this, proto.IQ_Packet, 2));
};


/** @param {?proto.IQ_Packet|undefined} value */
proto.Packet.prototype.setIqPacket = function(value) {
  jspb.Message.setOneofWrapperField(this, 2, proto.Packet.oneofGroups_[0], value);
};


proto.Packet.prototype.clearIqPacket = function() {
  this.setIqPacket(undefined);
};


/**
 * Returns whether this field is set.
 * @return {!boolean}
 */
proto.Packet.prototype.hasIqPacket = function() {
  return jspb.Message.getField(this, 2) != null;
};


/**
 * optional FFT_Packet fft_packet = 3;
 * @return {?proto.FFT_Packet}
 */
proto.Packet.prototype.getFftPacket = function() {
  return /** @type{?proto.FFT_Packet} */ (
    jspb.Message.getWrapperField(this, proto.FFT_Packet, 3));
};


/** @param {?proto.FFT_Packet|undefined} value */
proto.Packet.prototype.setFftPacket = function(value) {
  jspb.Message.setOneofWrapperField(this, 3, proto.Packet.oneofGroups_[0], value);
};


proto.Packet.prototype.clearFftPacket = function() {
  this.setFftPacket(undefined);
};


/**
 * Returns whether this field is set.
 * @return {!boolean}
 */
proto.Packet.prototype.hasFftPacket = function() {
  return jspb.Message.getField(this, 3) != null;
};


/**
 * optional PDW_Packet pdw_packet = 4;
 * @return {?proto.PDW_Packet}
 */
proto.Packet.prototype.getPdwPacket = function() {
  return /** @type{?proto.PDW_Packet} */ (
    jspb.Message.getWrapperField(this, proto.PDW_Packet, 4));
};


/** @param {?proto.PDW_Packet|undefined} value */
proto.Packet.prototype.setPdwPacket = function(value) {
  jspb.Message.setOneofWrapperField(this, 4, proto.Packet.oneofGroups_[0], value);
};


proto.Packet.prototype.clearPdwPacket = function() {
  this.setPdwPacket(undefined);
};


/**
 * Returns whether this field is set.
 * @return {!boolean}
 */
proto.Packet.prototype.hasPdwPacket = function() {
  return jspb.Message.getField(this, 4) != null;
};


