/**
 * @fileoverview
 * @enhanceable
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!

goog.provide('proto.Packet_Header');
goog.provide('proto.Packet_Header.PacketType');

goog.require('jspb.BinaryReader');
goog.require('jspb.BinaryWriter');
goog.require('jspb.Message');


/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.Packet_Header = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.Packet_Header, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  proto.Packet_Header.displayName = 'proto.Packet_Header';
}


if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.Packet_Header.prototype.toObject = function(opt_includeInstance) {
  return proto.Packet_Header.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.Packet_Header} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.Packet_Header.toObject = function(includeInstance, msg) {
  var f, obj = {
    type: jspb.Message.getField(msg, 1),
    fs: jspb.Message.getField(msg, 2),
    fc: jspb.Message.getField(msg, 3)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.Packet_Header}
 */
proto.Packet_Header.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.Packet_Header;
  return proto.Packet_Header.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.Packet_Header} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.Packet_Header}
 */
proto.Packet_Header.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {!proto.Packet_Header.PacketType} */ (reader.readEnum());
      msg.setType(value);
      break;
    case 2:
      var value = /** @type {number} */ (reader.readUint32());
      msg.setFs(value);
      break;
    case 3:
      var value = /** @type {number} */ (reader.readUint32());
      msg.setFc(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.Packet_Header.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.Packet_Header.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.Packet_Header} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.Packet_Header.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = /** @type {!proto.Packet_Header.PacketType} */ (jspb.Message.getField(message, 1));
  if (f != null) {
    writer.writeEnum(
      1,
      f
    );
  }
  f = /** @type {number} */ (jspb.Message.getField(message, 2));
  if (f != null) {
    writer.writeUint32(
      2,
      f
    );
  }
  f = /** @type {number} */ (jspb.Message.getField(message, 3));
  if (f != null) {
    writer.writeUint32(
      3,
      f
    );
  }
};


/**
 * @enum {number}
 */
proto.Packet_Header.PacketType = {
  IQ: 0,
  FFT: 1,
  PDW: 2
};

/**
 * required PacketType type = 1;
 * @return {!proto.Packet_Header.PacketType}
 */
proto.Packet_Header.prototype.getType = function() {
  return /** @type {!proto.Packet_Header.PacketType} */ (jspb.Message.getFieldWithDefault(this, 1, 0));
};


/** @param {!proto.Packet_Header.PacketType} value */
proto.Packet_Header.prototype.setType = function(value) {
  jspb.Message.setField(this, 1, value);
};


proto.Packet_Header.prototype.clearType = function() {
  jspb.Message.setField(this, 1, undefined);
};


/**
 * Returns whether this field is set.
 * @return {!boolean}
 */
proto.Packet_Header.prototype.hasType = function() {
  return jspb.Message.getField(this, 1) != null;
};


/**
 * required uint32 fs = 2;
 * @return {number}
 */
proto.Packet_Header.prototype.getFs = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 2, 0));
};


/** @param {number} value */
proto.Packet_Header.prototype.setFs = function(value) {
  jspb.Message.setField(this, 2, value);
};


proto.Packet_Header.prototype.clearFs = function() {
  jspb.Message.setField(this, 2, undefined);
};


/**
 * Returns whether this field is set.
 * @return {!boolean}
 */
proto.Packet_Header.prototype.hasFs = function() {
  return jspb.Message.getField(this, 2) != null;
};


/**
 * required uint32 fc = 3;
 * @return {number}
 */
proto.Packet_Header.prototype.getFc = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 3, 0));
};


/** @param {number} value */
proto.Packet_Header.prototype.setFc = function(value) {
  jspb.Message.setField(this, 3, value);
};


proto.Packet_Header.prototype.clearFc = function() {
  jspb.Message.setField(this, 3, undefined);
};


/**
 * Returns whether this field is set.
 * @return {!boolean}
 */
proto.Packet_Header.prototype.hasFc = function() {
  return jspb.Message.getField(this, 3) != null;
};


